name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'

env:
  GO_VERSION: 1.18

jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Continous Integration'
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout Repository'
    - uses: actions/setup-go@v3
      name:  Install go ${{ env.GO_VERSION }}
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install go test framework 
      run: 'go install github.com/stretchr/gorc'
    - name: 'Run Tests'
      run: gorc

    - name: "Publish Code Coverage"
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md