name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'

env:
  GO_VERSION: 1.18

jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Continous Integration'
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout Repository'
    - uses: actions/setup-go@v3
      name:  Install go ${{ env.GO_VERSION }}
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: 'Build Solution'
      run: go build -v -o app -race ./backend
    - name: 'Test Solution'
      run: go test -v ./backend