name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'

env:
  GO_VERSION: 1.18
  APP: backend
  APP_NAME: webappclockorocklab001

jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'CI / Tests'
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout Repository'
    - uses: actions/setup-go@v3
      name:  Install go ${{ env.GO_VERSION }}
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: 'Build Solution'
      run: go build -v -o app -race ./$APP
    - name: 'Test Solution'
      run: go test -v ./$APP
  
  container-build:
    name: 'CI / Docker'
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set docker tag
        run: |
          export DOCKERTAG="${{ secrets.ACR_ENDPOINT }}/$APP:$GITHUB_SHA"
          echo "DOCKERTAG=${DOCKERTAG}" >> $GITHUB_ENV
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and cache image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ env.APP }}
          push: ${{ github.ref_name == 'main' }}
          tags: '${{ env.DOCKERTAG }}'
  
  publish-container:
    name: 'CD / App Service'
    needs: container-build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
    - name: Set docker tag
      run: |
        export DOCKERTAG="${{ secrets.ACR_ENDPOINT }}/$APP:$GITHUB_SHA"
        echo "DOCKERTAG=${DOCKERTAG}" >> $GITHUB_ENV
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      name: 'Deploy Container'
      with:
        app-name: '${{ env.APP_NAME }}'
        images: '${{ env.DOCKERTAG }}'
           