name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'

env:
  GO_VERSION: 1.18
  APP: backend

jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'Continous Integration'
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout Repository'
    - uses: actions/setup-go@v3
      name:  Install go ${{ env.GO_VERSION }}
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: 'Build Solution'
      run: go build -v -o app -race ./$APP
    - name: 'Test Solution'
      run: go test -v ./$APP
  
  container-build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      dockertag: ${{ steps.output.outputs.dockertag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Export dockertag
        run: |
          export DOCKERTAG="${{ secrets.ACR_ENDPOINT }}/$APP:$GITHUB_SHA"
          echo "DOCKERTAG=${DOCKERTAG}" >> $GITHUB_ENV
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and cache image
        uses: docker/build-push-action@v3
        with:
          context: ./$APP
          push: true
          tags: '${{ env.DOCKERTAG }}'
      - name: Set output
        id: output
        run: echo "::set-output name=dockertag::${{ env.DOCKERTAG }}"