# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappclockorocklab001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://acrclockorock001.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ec0b286f4fd476d9caf88e3d0430500 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_582277661c854489a39257ea932fb982 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: acrclockorock001.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ec0b286f4fd476d9caf88e3d0430500 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappclockorocklab001'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7ad6c7a8a19a465c9fc4c4679eaece05 }}
        images: 'acrclockorock001.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ec0b286f4fd476d9caf88e3d0430500 }}/backend:${{ github.sha }}'